---
title: "arma"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{arma}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lssm)
library(purrr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(caret)
```

We illustrate with an AR(1) model.

# Simulated Data

## Illustration of estimation and 1 step ahead prediction intervals.

```{r}
y <- arima.sim(model = list(ar = c(.2, .5, .05), ma = .9), n = 200)

arma_fit <- fit_lssm(
  y = y,
  model = "arma",
  transformation = "none",
  p_ar = 3,
  q_ma = 1,
  verbose = FALSE)

forecasts <- predict(
  arma_fit,
  horizon = 1,
  forecast_representation = "quantile",
  quantile_levels = c(0.025, 0.25, 0.5, 0.75, 0.975))

plot_data <- data.frame(
  t = seq_len(200),
  y = as.vector(y)
)

ggplot() +
  geom_line(data = plot_data, mapping = aes(x = t, y = y)) +
  geom_errorbar(
    data = data.frame(t = 201, ymin = forecasts[1, 1], ymax = forecasts[1, 5]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "cornflowerblue",
    width = 3
  ) +
  geom_errorbar(
    data = data.frame(t = 201, ymin = forecasts[1, 2], ymax = forecasts[1, 4]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "orange",
    width = 2
  ) +
  geom_point(
    data = data.frame(t = 201, y = forecasts[1, 3]),
    mapping = aes(x = t, y = y)
  ) +
  theme_bw()
```

## Sampling distributions of estimators

We estimate from many simulated data sets.

```{r}
set.seed(84773)
n_replicates <- 1000

estimates <- purrr::map_dfr(
  seq_len(n_replicates),
  function(i) {
    print(paste0("replicate number ", i))
    y <- arima.sim(model = list(ar = c(.2, .5, .05), ma = .9 ), n = 200)

    arma_fit <- fit_lssm(
      y = y,
      model = "arma",
      transformation = "none",
      p_ar = 3,
      q_ma = 1,
      verbose = FALSE)

    arma_fit$param_estimates %>% as.list() %>% as.data.frame()
  }
)
```

```{r}
estimates$sd_zeta <- sqrt(estimates$var_zeta)

true_pars <- list(
  "phi.1." = 0.2,
  "phi.2." = 0.5,
  "phi.3." = 0.05,
  "theta.1." = 0.9,
  "var_zeta" = 1.0,
  "sd_zeta" = 1.0
)

plots <- purrr::map(
  names(true_pars),
  function(par_name) {
    ggplot() +
      geom_histogram(
        data = estimates,
        mapping = aes_string(x = par_name)
      ) +
      geom_vline(xintercept = true_pars[[par_name]]) +
      theme_bw()
  }
)

grid.arrange(grobs = plots)
```


# Using cross-validation via `caret` to select model

```{r}
y <- arima.sim(model = list(ar = c(.2, .5, .05), ma = .9), n = 200)

y <- as.numeric(y)
x <- matrix(y)
colnames(x) <- "y"

arma_fit <- train(
  x = x,
  y = y,
  method = lssm_arma_caret,
  verbose = FALSE,
  metric = "log_score",
  maximize = TRUE,
  trControl = trainControl(
    method = "timeslice",
    number = 50, # number of folds for cross-validation
    initialWindow = 150,
    horizon = 1,
    fixedWindow = FALSE,
    returnResamp = "all", # return information from cross-validation
    savePredictions = TRUE,
    summaryFunction = log_score_summary
  ),
  tuneGrid = arma_param_grid(
    x = y,
    y = y,
    transformation = "none",
    transform_offset = 0.0,
    max_d = 2,
    max_D = 0,
    max_p_ar = 4,
    max_q_ma = 4,
    min_order = 1,
    max_order = 5
  )
)
```

```{r}
arma_fit
```

```{r}
xval_forecasts <- predict(
  arma_fit$finalModel,
  horizon = 1,
  forecast_representation = "quantile",
  quantile_levels = c(0.025, 0.25, 0.5, 0.75, 0.975))

plot_data <- data.frame(
  t = seq_len(200),
  y = as.vector(y)
)

p_xval_fit <- ggplot() +
  geom_line(data = plot_data, mapping = aes(x = t, y = y)) +
  geom_errorbar(
    data = data.frame(t = 201, ymin = xval_forecasts[1, 1], ymax = xval_forecasts[1, 5]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "cornflowerblue",
    width = 3
  ) +
  geom_errorbar(
    data = data.frame(t = 201, ymin = xval_forecasts[1, 2], ymax = xval_forecasts[1, 4]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "orange",
    width = 2
  ) +
  geom_point(
    data = data.frame(t = 201, y = xval_forecasts[1, 3]),
    mapping = aes(x = t, y = y)
  ) +
  ggtitle("Forecast from model selected by cross-validation") +
  theme_bw()


```

```{r}
correct_arma_fit <- fit_lssm(
  y = y,
  ts_frequency = 1,
  model = "arma",
  transformation = "none",
  p_ar = 3,
  q_ma = 1,
  verbose = FALSE)

correct_forecasts <- predict(
  correct_arma_fit,
  horizon = 1,
  forecast_representation = "quantile",
  quantile_levels = c(0.025, 0.25, 0.5, 0.75, 0.975))

p_correct_fit <- ggplot() +
  geom_line(data = plot_data, mapping = aes(x = t, y = y)) +
  geom_errorbar(
    data = data.frame(t = 201, ymin = correct_forecasts[1, 1], ymax = correct_forecasts[1, 5]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "cornflowerblue",
    width = 3
  ) +
  geom_errorbar(
    data = data.frame(t = 201, ymin = correct_forecasts[1, 2], ymax = correct_forecasts[1, 4]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "orange",
    width = 2
  ) +
  geom_point(
    data = data.frame(t = 201, y = correct_forecasts[1, 3]),
    mapping = aes(x = t, y = y)
  ) +
  ggtitle("Forecast from correctly specified model fit") +
  theme_bw()

```


```{r}
dgp <- correct_arma_fit
dgp$param_estimates[["phi[1]"]] <- .2
dgp$param_estimates[["phi[2]"]] <- .5
dgp$param_estimates[["phi[3]"]] <- .05
dgp$param_estimates[["theta[1]"]] <- .9
dgp$param_estimates[["var_zeta"]] <- 1.0


dgp_forecasts <- predict(
  dgp,
  horizon = 1,
  forecast_representation = "quantile",
  quantile_levels = c(0.025, 0.25, 0.5, 0.75, 0.975))

p_dgp <- ggplot() +
  geom_line(data = plot_data, mapping = aes(x = t, y = y)) +
  geom_errorbar(
    data = data.frame(t = 201, ymin = dgp_forecasts[1, 1], ymax = dgp_forecasts[1, 5]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "cornflowerblue",
    width = 3
  ) +
  geom_errorbar(
    data = data.frame(t = 201, ymin = dgp_forecasts[1, 2], ymax = dgp_forecasts[1, 4]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "orange",
    width = 2
  ) +
  geom_point(
    data = data.frame(t = 201, y = dgp_forecasts[1, 3]),
    mapping = aes(x = t, y = y)
  ) +
  ggtitle("Forecast from data generating process") +
  theme_bw()

```

```{r}
grid.arrange(p_xval_fit, p_correct_fit, p_dgp)
```

```{r}
bind_rows(
  as.data.frame(xval_forecasts) %>% mutate(model = "crossval selected"),
  as.data.frame(correct_forecasts) %>% mutate(model = "correct model, estimated"),
  as.data.frame(dgp_forecasts) %>% mutate(model = "dgp")
)
```

