---
title: "covid_arma"
author: "Serena Wang"
date: "9/8/2020"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lssm)
library(purrr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(readr)
```

```{r}
y <- read_csv("2020-09-07-US-deaths.csv") %>%
  dplyr::filter(date >= '2020-02-28')

inds <- seq(min(y$date), max(y$date), by = "day")

y_ts <- ts(y$inc, start =1, frequency = 365)
arma_fit <- fit_lssm(
  y = y_ts,
  model = "arma",
  transformation = "log",
  p_ar = 2,
  q_ma = 2,
  verbose = FALSE)

forecasts <- predict(
  arma_fit,
  horizon = 1,
  forecast_representation = "quantile",
  quantile_levels = c(0.025, 0.25, 0.5, 0.75, 0.975))

plot_data <- data.frame(
  #t = seq_len(192),
  t = inds,
  y = as.vector(y_ts)
)

ggplot() +
  geom_line(data = plot_data, mapping = aes(x = t, y = y)) +
  geom_errorbar(
    data = data.frame(t = max(inds)+1, ymin = forecasts[1, 1], ymax = forecasts[1, 5]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "cornflowerblue",
    width = 3
  ) +
  geom_errorbar(
    data = data.frame(t = max(inds)+1, ymin = forecasts[1, 2], ymax = forecasts[1, 4]),
    mapping = aes(x = t, ymin = ymin, ymax = ymax),
    color = "orange",
    width = 2
  ) +
  geom_point(
    data = data.frame(t = max(inds)+1, y = forecasts[1, 3]),
    mapping = aes(x = t, y = y)
  ) +
  theme_bw()
```